#!/bin/bash
# Project: Elewon Game Server Installer - ElewonGSI
# Author: Can Sahin
# License: MIT License, see LICENSE.md
# Documentation: https://docs.elewon.net
# Website: https://elewon.net

# DO NOT EDIT THIS FILE
# https://docs.elewon.net

set -e
source <(curl -sSL https://colors.get.elewon.net) > /dev/null 2>&1

sudo apt update && sudo apt upgrade -y
clear
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] Updating Unturned Server...${NC}"
sleep 1
~/Unturned/steamcmd/steamcmd.sh +login anonymous +app_update 1110390 +quit
sleep 1
echo -e "${GRAY}[${GREEN}OK${GRAY}] Unturned Server Update Complete...${NC}"