#!/bin/bash
# Project: Elewon Game Server Installer - ElewonGSI
# Author: Can Sahin
# License: MIT License, see LICENSE.md
# Documentation: https://docs.elewon.net
# Website: https://elewon.net

# DO NOT EDIT THIS FILE
# https://docs.elewon.net

function handle_error {
    echo -e "${GRAY}[${YELLOW}ALERT${GRAY}] ${RED}ERROR: Command failed -> '${BASH_COMMAND}' (line: ${BASH_LINENO[0]})${NC}"
}
trap handle_error ERR
set -e

source <(curl -sSL https://colors.get.elewon.net) > /dev/null 2>&1
sudo apt update && sudo apt upgrade -y
clear
sleep 1
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Preparing installation folders...${NC}"
mkdir -p ~/Unturned > /dev/null 2>&1
mkdir -p ~/Unturned/steamcmd > /dev/null 2>&1
mkdir -p ~/Unturned/unturned_server > /dev/null 2>&1
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Installation folders are ready....${NC}"
sleep 1
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Downloading required libraries...${NC}"
sudo dpkg --add-architecture i386 > /dev/null 2>&1
sudo apt install -y lib32gcc-s1 curl wget tar ca-certificates > /dev/null 2>&1
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Required libraries have been downloaded...${NC}"
sleep 1
echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Downloading SteamCMD...${NC}"
cd ~/Unturned/steamcmd > /dev/null 2>&1
if [ ! -f steamcmd.sh ]; then > /dev/null 2>&1
    wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz > /dev/null 2>&1
    tar -xvzf steamcmd_linux.tar.gz > /dev/null 2>&1
    echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}SteamCMD has been downloaded...${NC}"
else
    echo -e "${RED}SteamCMD already exists, it is skipped.${NC}"
fi
sleep 1

echo -e "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Downloading Unturned server, Please wait! (AppID: 1110390)...${NC}"
~/Unturned/steamcmd/steamcmd.sh +login anonymous +force_install_dir ~/Unturned/unturned_server +app_update 1110390 validate +quit
cd ~/Unturned/unturned_server > /dev/null 2>&1
sudo wget https://raw.githubusercontent.com/elewonn/ElewonGSI/refs/heads/main/game-servers/Unturned/install/start.sh > /dev/null 2>&1
sudo chmod +x start.sh > /dev/null 2>&1
cd ~/Unturned > /dev/null 2>&1
sudo wget https://raw.githubusercontent.com/elewonn/ElewonGSI/refs/heads/main/game-servers/Unturned/install/unturned_update.sh > /dev/null 2>&1
sudo chmod +x unturned_update.sh > /dev/null 2>&1
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}The Unturned server has been downloaded successfully.${NC}"
sleep 1
echo
echo -e "${RED}----------------------------------------------------------${NC}"
echo -e "${GRAY}[${YELLOW}INFO${GRAY}]${GREEN} To start the server:${NC}"
echo
echo -e "${LAVENDER_GRAY}cd ~/Unturned/unturned_server${NC}"
echo -e "${LAVENDER_GRAY}./start.sh${NC}"
echo -e "${RED}----------------------------------------------------------${NC}"
echo -e "${GRAY}[${YELLOW}INFO${GRAY}]${GREEN} Unturned server update:${NC}"
echo
echo -e "${LAVENDER_GRAY}cd ~/Unturned${NC}"
echo -e "${LAVENDER_GRAY}./unturned_update.sh${NC}"
echo
echo -e "${GREEN}📁 To configure the server: ~/Unturned/unturned_server/Servers/DefaultServer${NC}"
