#!/bin/bash
# Project: Elewon Game Server Installer - ElewonGSI
# Author: Can Sahin
# License: MIT License, see LICENSE.md
# Documentation: https://docs.elewon.net
# Website: https://elewon.net

# DO NOT EDIT THIS FILE
# https://docs.elewon.net

function handle_error {
    echo -e "${GRAY}[${YELLOW}ALERT${GRAY}] ${RED}ERROR: Command failed -> '${BASH_COMMAND}' (line: ${BASH_LINENO[0]})${NC}"
}
trap handle_error ERR
set -e
source <(curl -sSL http://raw.githubusercontent.com/elewonn/ElewonGSI/refs/heads/main/colors/colors.sh) > /dev/null 2>&1
sudo apt update && sudo apt upgrade -y
clear
echo -ne "${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Updating Unturned Server${NC}"
(
  ~/Unturned/steamcmd/steamcmd.sh +login anonymous +app_update 1110390 +quit
) &
PID=$!
while kill -0 $PID 2>/dev/null; do
  for dots in "." ".." "..."; do
    echo -ne "\r${GRAY}[${YELLOW}INFO${GRAY}] ${LAVENDER_GRAY}Updating Unturned Server$dots${NC}   "
    sleep 0.5
  done
done
clear
sleep 1
echo -e "${GRAY}[${GREEN}OK${GRAY}] ${LAVENDER_GRAY}Unturned Server Update Complete...${NC}"
